import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import process from 'node:process';
import readline from 'node:readline/promises';
import { stdin as defaultStdin, stdout as defaultStdout } from 'node:process';
import { CLIError, DEFAULT_BASE_URL, Salta7Client, validateBaseUrl } from './client.js';
import { buildHumanizeConfig } from './humanize.js';
import { setLanguage, t } from './i18n.js';
import { printResult } from './output.js';
import { checkForUpdate, installUpdate } from './updater.js';

export const VERSION='0.3.0';
const TERMINAL=new Set(['completed','partial','failed','cancelled','canceled']);
const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));

function languageFromArgv(argv){ for(let i=0;i<argv.length;i+=1){ if(argv[i].startsWith('--lang='))return argv[i].slice(7); if(argv[i]==='--lang'&&argv[i+1])return argv[i+1]; } return 'auto'; }
function usage(){ return `Salta7 CLI Node (${VERSION}) — ${t('description')}\n\n${t('usage')}:\n  s7-node [global options] <command> [args]\n\n${t('globalOptions')}:\n  --lang auto|en|ja|ko|hi\n  --base-url URL\n  --token TOKEN\n  --timeout SECONDS\n  --retries N\n  --allow-insecure-http\n  --json | --jsonl | --compact\n  --no-color\n  --reveal-secrets\n\n${t('commands')}:\n  menu\n  doctor\n  prices\n  stock [product]\n  balance\n  buy [product] [amount] [--yes]\n  history\n  history-items <tx_id>\n  update [--check] [--yes]\n  task quote\n  task products [--tool join|humanize]\n  task active\n  task status <job_id> [--watch] [--interval SECONDS]\n  task history [--tool boost|join|humanize] [--limit N]\n  task items <job_id> [--byot]\n  task byot-quote --tokens-file FILE [--boosts-needed N] [--humanize]\n  task boost --mode stock|byot --invite INVITE [options]\n  task join --mode stock|byot --invite INVITE [options]\n  task humanize --mode stock|byot [options]\n`; }
function takeValue(argv,index,name){ const arg=argv[index]; if(arg.startsWith(`${name}=`))return [arg.slice(name.length+1),index]; if(arg===name){ if(argv[index+1]===undefined)throw new CLIError(`${name} requires a value.`); return [argv[index+1],index+1]; } return undefined; }
function parseArgs(argv){ const global={baseUrl:process.env.SALTA7_BASE_URL??DEFAULT_BASE_URL,token:process.env.SALTA7_TOKEN,timeoutMs:30_000,retries:3,allowInsecureHttp:false,json:false,jsonl:false,compact:false,noColor:false,revealSecrets:false,lang:languageFromArgv(argv)}; const rest=[]; const valueOptions=new Map([['--base-url',(v)=>{global.baseUrl=v;}],['--token',(v)=>{global.token=v;}],['--timeout',(v)=>{global.timeoutMs=Number(v)*1000;}],['--retries',(v)=>{global.retries=Number(v);} ],['--lang',(v)=>{global.lang=v;}]]); let commandSeen=false; for(let i=0;i<argv.length;i+=1){ const arg=argv[i]; if(!commandSeen){ let handled=false; for(const [name,setter] of valueOptions){ const found=takeValue(argv,i,name); if(found){setter(found[0]);i=found[1];handled=true;break;} } if(handled)continue; if(arg==='--allow-insecure-http'){global.allowInsecureHttp=true;continue;} if(arg==='--json'){global.json=true;continue;} if(arg==='--jsonl'){global.jsonl=true;continue;} if(arg==='--compact'){global.compact=true;global.json=true;continue;} if(arg==='--no-color'){global.noColor=true;continue;} if(arg==='--reveal-secrets'){global.revealSecrets=true;continue;} if(arg==='--help'||arg==='-h'||arg==='--version'){rest.push(arg);continue;} if(arg.startsWith('-'))throw new CLIError(t('unknownOption',{option:arg})); commandSeen=true; }
    rest.push(arg);
  } return {global,rest}; }
function parseCommandOptions(args){ const options={},positional=[]; const boolean=new Set(['--yes','-y','--byot','--humanize','--watch','--wait','--random-all','--random-avatar','--random-name','--random-bio','--random-pronouns','--random-hypesquad','--check']); const values=new Set(['--tool','--limit','--tokens-file','--boosts-needed','--mode','--invite','--boosts','--product','--quantity','--interval','--client-tx-id','--avatar-url','--avatar-file','--banner-file','--banner-data','--name','--bio','--pronouns','--hypesquad','--humanize-json']); for(let i=0;i<args.length;i+=1){ const arg=args[i]; if(boolean.has(arg)){options[arg.replace(/^-+/,'')]=true;continue;} const eq=arg.indexOf('='); const name=eq>=0?arg.slice(0,eq):arg; if(values.has(name)){const value=eq>=0?arg.slice(eq+1):args[++i];if(value===undefined)throw new CLIError(`${name} requires a value.`);options[name.slice(2)]=value;continue;} if(arg.startsWith('-'))throw new CLIError(t('unknownOption',{option:arg})); positional.push(arg); } return {options,positional}; }
function noExtra(positional,count){ if(positional.length>count)throw new CLIError(t('unexpectedArg',{arg:positional[count]})); }
function integer(value,fallback){if(value===undefined)return fallback;const n=Number(value);return Number.isInteger(n)?n:Number.NaN;}
function jsonMode(global){return Boolean(global.json||global.jsonl||global.compact);}
function tty(runtime){return Boolean(runtime.isTTY??(runtime.stdin?.isTTY&&runtime.stdout?.isTTY));}
async function ask(runtime,question){ if(runtime.prompt)return runtime.prompt(question); const rl=readline.createInterface({input:runtime.stdin,output:runtime.stdout}); try{return await rl.question(question);}finally{rl.close();} }
async function confirm(runtime,question){const answer=(await ask(runtime,`${question} [y/N]: `)).trim().toLowerCase();return ['y','yes','はい','h','예','네','हाँ','हां'].includes(answer);}
function warn(io,msg){(io.warn??io.error??io.log).call(io,`${t('warning')}: ${msg}`);}
async function tokenPermissionWarning(file,io){ if(process.platform==='win32')return; try{const st=await fs.stat(file);const mode=st.mode&0o777;if(mode&0o077)warn(io,t('tokenPerm',{mode:`0${mode.toString(8)}`,path:file}));}catch{/* read path error handled separately */} }
async function loadTokens(file,io){ if(!file)throw new CLIError(t('tokensFileRequired')); await tokenPermissionWarning(file,io); let text; try{text=await fs.readFile(file,'utf8');}catch{throw new CLIError(t('readFile',{path:file}));} const tokens=text.split(/\r?\n/).map((s)=>s.trim()).filter(Boolean); if(!tokens.length)throw new CLIError(t('tokensEmpty')); if(tokens.length>100)throw new CLIError(t('tokensMax')); return tokens; }
function humanizeValues(o){return {randomAll:o['random-all'],randomAvatar:o['random-avatar'],avatarUrl:o['avatar-url'],avatarFile:o['avatar-file'],bannerFile:o['banner-file'],bannerData:o['banner-data'],randomName:o['random-name'],name:o.name,randomBio:o['random-bio'],bio:o.bio,randomPronouns:o['random-pronouns'],pronouns:o.pronouns,randomHypesquad:o['random-hypesquad'],hypesquad:o.hypesquad,humanizeJson:o['humanize-json']};}
function productEntries(data){ const source=Array.isArray(data)?data:(Array.isArray(data?.products)?data.products:Object.entries(data??{}).map(([key,value])=>typeof value==='object'&&value?{product:key,...value}:{product:key,value})); return source.map((item)=>({name:String(item?.account??item?.product??item?.name??item?.id??item),raw:item})); }
async function chooseProduct(client,tool,runtime,io){ const data=tool?await client.taskProducts(tool):await client.prices(); const entries=productEntries(data); if(!entries.length)throw new CLIError('No products available.'); io.log(tool?t('selectTaskProduct'):t('selectProduct')); entries.forEach((e,i)=>io.log(`  ${i+1}. ${e.name}`)); const n=Number(await ask(runtime,'> ')); if(!Number.isInteger(n)||n<1||n>entries.length)throw new CLIError(t('invalidChoice')); return entries[n-1].name; }
async function askInt(runtime,label,min,max){const n=Number(await ask(runtime,`${label} (${min}-${max}): `));if(!Number.isInteger(n)||n<min||n>max)throw new CLIError(`${label} must be between ${min} and ${max}.`);return n;}
async function waitForJob(client,jobId,intervalSeconds,output,{heartbeatMs=60_000,now=()=>Date.now(),sleepImpl=sleep}={}){if(!jobId)throw new CLIError(t('jobIdRequired'));if(!Number.isFinite(intervalSeconds)||intervalSeconds<=0)throw new CLIError(t('intervalPositive'));let last='',lastPrint=0;while(true){const job=await client.taskStatus(jobId);const sig=JSON.stringify([job?.status,job?.boosts_delivered,job?.delivered,job?.humanized,job?.failed_count,job?.error,job?.message,job?.reason]);const status=String(job?.status??'').toLowerCase();const ts=now();if(sig!==last||TERMINAL.has(status)||ts-lastPrint>=heartbeatMs){output(job);lastPrint=ts;}last=sig;if(TERMINAL.has(status))return job;await sleepImpl(intervalSeconds*1000);}}
async function maybeWait(client,result,options,output){output(result);if(!options.wait)return;if(!result||typeof result!=='object'||!result.job_id)throw new CLIError(t('noJobId'));if(!TERMINAL.has(String(result.status??'').toLowerCase()))await waitForJob(client,String(result.job_id),Number(options.interval??10),output);}
async function runDoctor(client,global,io){const major=Number(process.versions.node.split('.')[0]);const checks=[{check:t('doctorNode'),ok:major>=22,value:process.versions.node},{check:t('doctorUrl'),ok:true,value:validateBaseUrl(global.baseUrl,{allowInsecureHttp:global.allowInsecureHttp})},{check:t('doctorFetch'),ok:typeof globalThis.fetch==='function',value:typeof globalThis.fetch==='function'?t('ok'):t('failed')},{check:t('doctorToken'),ok:Boolean(global.token),value:global.token?t('configured'):t('missing')}];try{await client.prices();checks.push({check:t('doctorApi'),ok:true,value:t('ok')});}catch(error){checks.push({check:t('doctorApi'),ok:false,value:error.message});}return checks;}
async function interactiveMain(client,global,runtime,io){ if(!tty(runtime)||jsonMode(global))throw new CLIError('Interactive menu requires a TTY and human-readable output.'); io.log(`\n${t('menuTitle')}`); const menu=['prices','stock','balance','buy','history','task active','doctor','exit']; menu.forEach((v,i)=>io.log(`  ${i+1}. ${v}`)); const choice=Number(await ask(runtime,`${t('menuPrompt')}: `)); if(!Number.isInteger(choice)||choice<1||choice>menu.length)throw new CLIError(t('invalidChoice')); const selected=menu[choice-1]; if(selected==='exit')return 0; const mapped=selected.split(' '); return run([...mapped],io,runtime,{globalOverride:global,clientOverride:client}); }

export async function run(argv=process.argv.slice(2),io=console,runtime={},internal={}){
  runtime={stdin:runtime.stdin??defaultStdin,stdout:runtime.stdout??defaultStdout,...runtime}; setLanguage(languageFromArgv(argv)); let parsed; try{parsed=parseArgs(argv);}catch(error){io.error(`${t('error')}: ${error.message}`);return 1;} const global=internal.globalOverride??parsed.global; const rest=parsed.rest; setLanguage(global.lang);
  if(rest.includes('--version')){io.log(VERSION);return 0;} if(rest.includes('--help')||rest.includes('-h')){io.log(usage());return 0;}
  try{const client=internal.clientOverride??new Salta7Client(global);const output=(value)=>printResult(value,global,io); if(rest.length===0)return tty(runtime)&&!jsonMode(global)?interactiveMain(client,global,runtime,io):(io.log(usage()),0); const [command,...args]=rest;
    if(command==='menu'){noExtra(args,0);return interactiveMain(client,global,runtime,io);}
    if(command==='doctor'){noExtra(args,0);const checks=await runDoctor(client,global,io);output(checks);return checks.every((c)=>c.ok||c.check===t('doctorToken'))?0:1;}
    if(command==='prices'){noExtra(args,0);output(await client.prices());}
    else if(command==='stock'){const {positional}=parseCommandOptions(args);noExtra(positional,1);let account=positional[0];if(!account){if(!tty(runtime)||jsonMode(global))throw new CLIError('stock requires a product.');account=await chooseProduct(client,null,runtime,io);}output(await client.stock(account));}
    else if(command==='balance'){noExtra(args,0);output(await client.balance());}
    else if(command==='history'){noExtra(args,0);output(await client.history());}
    else if(command==='history-items'){const {positional}=parseCommandOptions(args);noExtra(positional,1);if(!positional[0])throw new CLIError('history-items requires tx_id.');output(await client.historyItems(positional[0]));}
    else if(command==='buy'){const {options,positional}=parseCommandOptions(args);noExtra(positional,2);let account=positional[0];let amount=positional[1]===undefined?undefined:Number(positional[1]);if(!account){if(!tty(runtime)||jsonMode(global))throw new CLIError(t('amountInvalid'));account=await chooseProduct(client,null,runtime,io);}if(amount===undefined&&tty(runtime)&&!jsonMode(global))amount=await askInt(runtime,'amount',1,10000);if(!Number.isInteger(amount)||amount<1||amount>10000)throw new CLIError(t('amountInvalid'));if(!options.yes&&!options.y){if(!tty(runtime))throw new CLIError(t('purchaseTty'));if(!await confirm(runtime,t('purchaseConfirm',{amount,product:account}))){io.log(t('cancelled'));return 0;}}output(await client.buy(account,amount,options['client-tx-id']??crypto.randomUUID()));}
    else if(command==='update'){const {options,positional}=parseCommandOptions(args);noExtra(positional,0);const info=await checkForUpdate(VERSION);if(jsonMode(global)){output(info);return 0;}if(!info.releaseFound){io.log(t('updateNone'));return 0;}if(!info.updateAvailable){io.log(t('updateCurrent',{version:VERSION}));return 0;}io.log(t('updateAvailable',{current:VERSION,latest:info.latestVersion}));if(options.check)return 0;if(!options.yes&&!options.y){if(!tty(runtime))throw new CLIError(t('updateTty'));if(!await confirm(runtime,t('updateConfirm',{latest:info.latestVersion})))return 0;}await installUpdate(info.tagName);io.log(t('updateDone',{latest:info.latestVersion}));}
    else if(command==='task'){const [sub,...subArgs]=args;if(!sub)throw new CLIError(t('unknownTask',{command:''}));const {options,positional}=parseCommandOptions(subArgs);
      if(sub==='quote'){noExtra(positional,0);output(await client.taskQuote());}
      else if(sub==='products'){noExtra(positional,0);if(options.tool&&!['join','humanize'].includes(options.tool))throw new CLIError('--tool must be join or humanize.');output(await client.taskProducts(options.tool));}
      else if(sub==='active'){noExtra(positional,0);output(await client.taskActive());}
      else if(sub==='status'){noExtra(positional,1);const id=positional[0];if(!id)throw new CLIError(t('jobIdRequired'));if(options.watch)await waitForJob(client,id,Number(options.interval??10),output);else output(await client.taskStatus(id));}
      else if(sub==='history'){noExtra(positional,0);const limit=integer(options.limit,10);if(!Number.isInteger(limit)||limit<1||limit>100)throw new CLIError('limit must be between 1 and 100.');if(options.tool&&!['boost','join','humanize'].includes(options.tool))throw new CLIError('--tool must be boost, join, or humanize.');output(await client.taskHistory(options.tool,limit));}
      else if(sub==='items'){noExtra(positional,1);if(!positional[0])throw new CLIError(t('jobIdRequired'));output(await client.taskItems(positional[0],Boolean(options.byot)));}
      else if(sub==='byot-quote'){noExtra(positional,0);const boostsNeeded=integer(options['boosts-needed'],0);if(!Number.isInteger(boostsNeeded)||boostsNeeded<0)throw new CLIError(t('boostsNegative'));output(await client.taskByotQuote(await loadTokens(options['tokens-file'],io),boostsNeeded,Boolean(options.humanize)));}
      else if(sub==='boost'){noExtra(positional,0);const mode=options.mode??'stock';if(!['stock','byot'].includes(mode)||!options.invite)throw new CLIError('boost requires --mode stock|byot and --invite.');const payload={tool:'boost',mode,invite:options.invite};if(mode==='stock'){const boosts=integer(options.boosts);if(!Number.isInteger(boosts)||boosts<1||boosts>40)throw new CLIError(t('boostStock'));payload.boosts=boosts;}else{payload.tokens=await loadTokens(options['tokens-file'],io);const n=integer(options['boosts-needed'],0);if(!Number.isInteger(n)||n<0)throw new CLIError(t('boostsNegative'));payload.boosts_needed=n;}const h=await buildHumanizeConfig(humanizeValues(options));if(h)payload.humanize=h;await maybeWait(client,await client.taskCreate(payload),options,output);}
      else if(sub==='join'){noExtra(positional,0);const mode=options.mode??'stock';if(!['stock','byot'].includes(mode)||!options.invite)throw new CLIError('join requires --mode stock|byot and --invite.');const payload={tool:'join',mode,invite:options.invite};if(mode==='stock'){let product=options.product;let q=integer(options.quantity);if(!product&&tty(runtime)&&!jsonMode(global))product=await chooseProduct(client,'join',runtime,io);if(q===undefined&&tty(runtime)&&!jsonMode(global))q=await askInt(runtime,'quantity',1,100);if(!product||!Number.isInteger(q)||q<1||q>100)throw new CLIError(t('joinStock'));Object.assign(payload,{product,quantity:q});}else payload.tokens=await loadTokens(options['tokens-file'],io);const h=await buildHumanizeConfig(humanizeValues(options));if(h)payload.humanize=h;await maybeWait(client,await client.taskCreate(payload),options,output);}
      else if(sub==='humanize'){noExtra(positional,0);const mode=options.mode??'stock';if(!['stock','byot'].includes(mode))throw new CLIError('humanize requires --mode stock|byot.');const payload={tool:'humanize',mode,humanize:await buildHumanizeConfig(humanizeValues(options),{required:true})};if(mode==='stock'){let product=options.product;let q=integer(options.quantity);if(!product&&tty(runtime)&&!jsonMode(global))product=await chooseProduct(client,'humanize',runtime,io);if(q===undefined&&tty(runtime)&&!jsonMode(global))q=await askInt(runtime,'quantity',1,100);if(!product||!Number.isInteger(q)||q<1||q>100)throw new CLIError(t('humanizeStock'));Object.assign(payload,{product,quantity:q});}else payload.tokens=await loadTokens(options['tokens-file'],io);await maybeWait(client,await client.taskCreate(payload),options,output);}
      else throw new CLIError(t('unknownTask',{command:sub}));
    }else throw new CLIError(t('unknownCommand',{command})); return 0;
  }catch(error){io.error(`${t('error')}: ${error instanceof Error?error.message:String(error)}`);return 1;}
}

export const _test={parseArgs,parseCommandOptions,waitForJob,tokenPermissionWarning,runDoctor};
